name: Generate HTML Table

on:
  workflow_dispatch:

jobs:
  generate-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run jq to filter JSON
        id: filter-json
        run: |
          mkdir -p $GITHUB_WORKSPACE/html
          jq '[.[] | select(.errorCount > 0) | {filePath,messages: [.messages[] | { ruleId: .ruleId, message,line,column}]}]' lint.json > errors.json
          cat errors.json

      - name: Generate HTML Table

        run: |
                  echo "<html><body><table border='1'><thead><tr><th>File Path</th><th>Rule ID</th><th>Message</th><th>Line</th><th>Column</th></tr></thead><tbody>" > $GITHUB_WORKSPACE/table.html
    
                      cat errors.json | jq -r 'group_by(.filePath)[] | "<tr><td>\(.[0].filePath)</td><td>\(.[].messages[].ruleId)</td><td>\(.[].messages[].message)</td><td>\(.[].messages[].line)</td><td>\(.[].messages[].column)</td></tr>"' >> $GITHUB_WORKSPACE/table.html
    
                   echo "</tbody></table></body></html>" >> $GITHUB_WORKSPACE/table.html




          


      - name: Display HTML Table
        run: cat $GITHUB_WORKSPACE/table.html >> $GITHUB_STEP_SUMMARY
