name: Run jq query

on:
 workflow_dispatch:

jobs:
  run-jq-query:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq
      
      - name: Run jq query
        run: |
          jq -r '["File Path", "Rule ID", "Message", "Line", "Column"], (.[] | [.filePath, .messages[].ruleId, .messages[].message, .messages[].line, .messages[].column]) | @tsv' lint.json > output.tsv
      
      - name: Display output
        run: cat output.tsv
